In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
df=pd.read_csv('/content/diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35  ...  33.6                     0.627   50        1
1            1       85             66             29  ...  26.6                     0.351   31        0
2            8      183             64              0  ...  23.3                     0.672   32        1
3            1       89             66             23  ...  28.1                     0.167   21        0
4            0      137             40             35  ...  43.1                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
df.shape

(768, 9)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
x=df.drop(columns='Outcome',axis=1)
y=df['Outcome']

In [ ]:

print(x)
print(y)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[76

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (614, 8) (154, 8)


In [ ]:
models=[LogisticRegression(),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def fun():
  for model in models:
    model.fit(x_train,y_train)
    test_data_prediction = model.predict(x_test)
    accuracy=accuracy_score(y_test,test_data_prediction)
    print(f"Accuracy score of the model - {model} : {accuracy}")

In [ ]:
fun()

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy score of the model - LogisticRegression() : 0.7402597402597403
Accuracy score of the model - SVC(kernel='linear') : 0.7272727272727273
Accuracy score of the model - KNeighborsClassifier() : 0.6883116883116883
Accuracy score of the model - RandomForestClassifier() : 0.7532467532467533


In [ ]:
#cross validation
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000),x,y,cv=5)


In [ ]:
print(cv_score_lr)

[0.77272727 0.74675325 0.75324675 0.81045752 0.77777778]


In [ ]:
mean_acc = sum(cv_score_lr)/len(cv_score_lr)
mean_acc=mean_acc * 100
mean_acc=round(mean_acc,2)
print(mean_acc)

77.22


In [ ]:
#support vector classifier
cv_score_svc = cross_val_score(SVC(kernel='linear'),x,y,cv=5)
print(cv_score_svc)
mean_acc_svc = sum(cv_score_svc)/len(cv_score_svc)
mean_acc_svc=mean_acc_svc * 100
mean_acc_svc =round(mean_acc_svc,2)
print(mean_acc_svc)

[0.75974026 0.75324675 0.74025974 0.81045752 0.76470588]
76.57


In [ ]:
# K-Neared neighbour
cv_score_knn = cross_val_score(KNeighborsClassifier(),x,y,cv=5)
print(cv_score_knn)
mean_acc_knn = sum(cv_score_knn)/len(cv_score_knn)
mean_acc_knn=mean_acc_knn * 100
mean_acc_knn =round(mean_acc_knn,2)
print(mean_acc_knn)

[0.72727273 0.72727273 0.7012987  0.75816993 0.70588235]
72.4


In [ ]:
#Random Forest
cv_score_rf = cross_val_score(RandomForestClassifier(),x,y,cv=5)
print(cv_score_rf)
mean_acc_rf = sum(cv_score_rf)/len(cv_score_rf)
mean_acc_rf=mean_acc_rf * 100
mean_acc_rf =round(mean_acc_rf,2)
print(mean_acc_rf)

[0.77272727 0.74675325 0.75974026 0.83006536 0.74509804]
77.09


Creating a function to compare the models


In [ ]:
models=[LogisticRegression(),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def compare_models_cross_validation():
  for model in models:
    cv_score = cross_val_score(model,x,y,cv=5)
    mean_acc =sum(cv_score)/len(cv_score)
    mean_acc= mean_acc * 100
    mean_acc = round(mean_acc,2)

    print("Cross validation accuracies for the model",model," : ",cv_score)
    print("Accuracy % of the model :",mean_acc,"%")
    print('-------------------------------------')

In [ ]:
compare_models_cross_validation()

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Cross validation accuracies for the model LogisticRegression()  :  [0.77272727 0.74675325 0.75974026 0.81699346 0.75163399]
Accuracy % of the model : 76.96 %
-------------------------------------
Cross validation accuracies for the model SVC(kernel='linear')  :  [0.75974026 0.75324675 0.74025974 0.81045752 0.76470588]
Accuracy % of the model : 76.57 %
-------------------------------------
Cross validation accuracies for the model KNeighborsClassifier()  :  [0.72727273 0.72727273 0.7012987  0.75816993 0.70588235]
Accuracy % of the model : 72.4 %
-------------------------------------
Cross validation accuracies for the model RandomForestClassifier()  :  [0.78571429 0.71428571 0.75324675 0.83660131 0.75163399]
Accuracy % of the model : 76.83 %
-------------------------------------
